---
# nombre que aparece en github
name: Checks
# significa que las acciones se ejecutan  al hacer push
on: [push]

jobs:
  test-lint:
    #  nombre que aparece en github
    name: Test and Lint
    # servidor en donde se ejecutaran las pruebas
    runs-on: ubuntu-20.04
    # pasos que se ejecutan en el trabajo
    steps:
    # iniciamos sesion
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          # verificamos
      - name: Checkout
        uses: actions/checkout@v2
        # corremos las pruebas
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"